services:
  db:
    image: mysql:8.0
    container_name: profile-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 4223
      MYSQL_DATABASE: profile
      MYSQL_USER: AzenDev
      MYSQL_PASSWORD: 4223
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: backend
    container_name: backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      db:
        condition: service_healthy # chỉ chạy khi db đã healthy

  frontend:
    build: frontend
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

volumes:
  db_data:
